// Generated by CoffeeScript 1.8.0
(function() {
  var bna, fs, path, through;

  fs = require("fs");

  path = require("path");

  through = require("through2");

  bna = require("bna");

  module.exports = function(marker, reactSrcFile, headerCode) {
    return through.obj(function(line, unused, cb) {
      var src, thisStream;
      if (line.indexOf(marker) !== -1) {
        src = bna.fuse(reactSrcFile, path.dirname(reactSrcFile), 'PageClass', {
          prependCode: headerCode
        })[0];
        thisStream = this;
        (function() {
          var Page, React, old;
          React = require("react");
          old = process.cwd();
          process.chdir(path.dirname(reactSrcFile));
          eval(src);
          Page = React.createFactory(this.PageClass);
          thisStream.push(React.renderToString(Page()));
          return process.chdir(old);
        })();
      } else {
        this.push(line);
      }
      return cb();
    });
  };

}).call(this);

//# sourceMappingURL=gulp-react.js.map
