// Generated by CoffeeScript 1.8.0
(function() {
  var byline, fs, pAttrs, path, through;

  fs = require("fs");

  path = require("path");

  byline = require("byline");

  through = require("through2");

  pAttrs = require("./parseAttrs");

  module.exports = function() {
    return through.obj(function(vfile, unused, cb) {
      var basedir;
      basedir = path.dirname(vfile.path);
      return fs.createReadStream(vfile.path).pipe(new byline.LineStream()).pipe(through.obj((function(_this) {
        return function(line, unused, cb) {
          var attrs, m;
          line = line + "\n";
          if ((m = /<(?:script|link)[ \t]+(.*?)[ \t]*>/.exec(line))) {
            attrs = pAttrs.parse(pAttrs.reTagAttr, m[1].toString());
            if (attrs.gulp) {
              attrs.gulp = pAttrs.parse(pAttrs.reGulp, attrs.gulp);
              attrs.basedir = basedir;
              attrs.relative = attrs.src || attrs.href;
              attrs._line = line.toString();
              _this.push(attrs);
            } else {
              _this.push(line);
            }
          } else {
            _this.push(line);
          }
          return cb();
        };
      })(this))).on('finish', cb);
    });
  };

}).call(this);

//# sourceMappingURL=gulp-line.js.map
